Keystone/config/routes.rb
Rails.application.routes.draw do
  resources :bid_sheets

  resources :misc_item_lines

  resources :accessory_lines

  resources :customers

  resources :concrete_slabs

  resources :misc_items

  resources :accessories

  resources :transfer_switches

  resources :generators

  resources :states

  resources :employees

end

Keystone/app/models/accessory.rb
class Accessory < ActiveRecord::Base
  has_many :bid_sheets
  has_many :accessory_lines, :through => :bid_sheets
end

Keystone/app/models/accessory_line.rb
class AccessoryLine < ActiveRecord::Base
  belongs_to :accessory
  belongs_to :bid_sheet
end

Keystone/app/models/bid_sheet.rb
class BidSheet < ActiveRecord::Base
  belongs_to :employee
  belongs_to :customer
  belongs_to :generator
  belongs_to :transfer_switch
  belongs_to :concrete_slab

  has_many :accessory_lines
  has_many :accessories, :through => :accessory_lines

  has_many :misc_item_lines
  has_many :misc_items, :through => :misc_item_lines
end

Keystone/app/models/concrete_slab.rb
class ConcreteSlab < ActiveRecord::Base
  has_many :bid_sheets
end

Keystone/app/models/customer.rb
class Customer < ActiveRecord::Base
  belongs_to :state
  has_many :bid_sheets
end

Keystone/app/models/employee.rb
class Employee < ActiveRecord::Base
  has_many :bid_sheets
end

Keystone/app/models/generator.rb
class Generator < ActiveRecord::Base
  has_many :bid_sheets
end

Keystone/app/models/misc_item.rb
class MiscItem < ActiveRecord::Base
  has_many :bid_sheets
  has_many :misc_item_lines, :through => :bid_sheets
end

Keystone/app/models/misc_item_line.rb
class MiscItemLine < ActiveRecord::Base
  belongs_to :misc_item
  belongs_to :bid_sheet
end

Keystone/app/models/state.rb
class State < ActiveRecord::Base
  has_many :customers
end

Keystone/app/models/transfer_switch.rb
class TransferSwitch < ActiveRecord::Base
  has_many :bid_sheets
end

Keystone/app/controllers/accessory_lines_controller.rb
class AccessoryLinesController < ApplicationController
  before_action :set_accessory_line, only: [:show, :edit, :update, :destroy]

  # GET /accessory_lines
  # GET /accessory_lines.json
  def index
    @accessory_lines = AccessoryLine.all
  end

  # GET /accessory_lines/1
  # GET /accessory_lines/1.json
  def show
  end

  # GET /accessory_lines/new
  def new
    @accessory_line = AccessoryLine.new
  end

  # GET /accessory_lines/1/edit
  def edit
  end

  # POST /accessory_lines
  # POST /accessory_lines.json
  def create
    @accessory_line = AccessoryLine.new(accessory_line_params)

    respond_to do |format|
      if @accessory_line.save
        format.html { redirect_to @accessory_line, notice: 'Accessory line was successfully created.' }
        format.json { render :show, status: :created, location: @accessory_line }
      else
        format.html { render :new }
        format.json { render json: @accessory_line.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /accessory_lines/1
  # PATCH/PUT /accessory_lines/1.json
  def update
    respond_to do |format|
      if @accessory_line.update(accessory_line_params)
        format.html { redirect_to @accessory_line, notice: 'Accessory line was successfully updated.' }
        format.json { render :show, status: :ok, location: @accessory_line }
      else
        format.html { render :edit }
        format.json { render json: @accessory_line.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accessory_lines/1
  # DELETE /accessory_lines/1.json
  def destroy
    @accessory_line.destroy
    respond_to do |format|
      format.html { redirect_to accessory_lines_url, notice: 'Accessory line was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_accessory_line
      @accessory_line = AccessoryLine.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def accessory_line_params
      params.require(:accessory_line).permit(:bidSheet_id, :accessory_id)
    end
end

Keystone/app/controllers/states_controller.rb
class StatesController < ApplicationController
  before_action :set_state, only: [:show, :edit, :update, :destroy]

  # GET /states
  # GET /states.json
  def index
    @states = State.all
  end

  # GET /states/1
  # GET /states/1.json
  def show
  end

  # GET /states/new
  def new
    @state = State.new
  end

  # GET /states/1/edit
  def edit
  end

  # POST /states
  # POST /states.json
  def create
    @state = State.new(state_params)

    respond_to do |format|
      if @state.save
        format.html { redirect_to @state, notice: 'State was successfully created.' }
        format.json { render :show, status: :created, location: @state }
      else
        format.html { render :new }
        format.json { render json: @state.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /states/1
  # PATCH/PUT /states/1.json
  def update
    respond_to do |format|
      if @state.update(state_params)
        format.html { redirect_to @state, notice: 'State was successfully updated.' }
        format.json { render :show, status: :ok, location: @state }
      else
        format.html { render :edit }
        format.json { render json: @state.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /states/1
  # DELETE /states/1.json
  def destroy
    @state.destroy
    respond_to do |format|
      format.html { redirect_to states_url, notice: 'State was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_state
      @state = State.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def state_params
      params.require(:state).permit(:name, :abbreviation)
    end
end

Keystone/app/helpers/accessories_helper.rb
module AccessoriesHelper
end

Keystone/app/helpers/accessory_lines_helper.rb
module AccessoryLinesHelper
end

Keystone/app/helpers/application_helper.rb
module ApplicationHelper
end

Keystone/app/helpers/bid_sheets_helper.rb
module BidSheetsHelper
end

Keystone/app/helpers/concrete_slabs_helper.rb
module ConcreteSlabsHelper
end

Keystone/app/helpers/customers_helper.rb
module CustomersHelper
end

Keystone/app/helpers/employees_helper.rb
module EmployeesHelper
end

Keystone/app/helpers/generators_helper.rb
module GeneratorsHelper
end

Keystone/app/helpers/misc_items_helper.rb
module MiscItemsHelper
end

Keystone/app/helpers/states_helper.rb
module StatesHelper
end

Keystone/app/views/accessory_lines/_form.html.erb
<%= form_for(@accessory_line) do |f| %>
  <% if @accessory_line.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@accessory_line.errors.count, "error") %> prohibited this accessory_line from being saved:</h2>

      <ul>
      <% @accessory_line.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :bidSheet_id %><br>
    <%= f.number_field :bidSheet_id %>
  </div>
  <div class="field">
    <%= f.label :accessory_id %><br>
    <%= f.number_field :accessory_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Keystone/app/views/accessory_lines/edit.html.erb
<h1>Editing accessory_line</h1>

<%= render 'form' %>

<%= link_to 'Show', @accessory_line %> |
<%= link_to 'Back', accessory_lines_path %>

Keystone/app/views/accessory_lines/index.html.erb
<h1>Listing accessory_lines</h1>

<table>
  <thead>
    <tr>
      <th>Bidsheet</th>
      <th>Accessory</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @accessory_lines.each do |accessory_line| %>
      <tr>
        <td><%= accessory_line.bidSheet_id %></td>
        <td><%= accessory_line.accessory_id %></td>
        <td><%= link_to 'Show', accessory_line %></td>
        <td><%= link_to 'Edit', edit_accessory_line_path(accessory_line) %></td>
        <td><%= link_to 'Destroy', accessory_line, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Accessory line', new_accessory_line_path %>

Keystone/app/views/accessory_lines/new.html.erb
<h1>New accessory_line</h1>

<%= render 'form' %>

<%= link_to 'Back', accessory_lines_path %>

Keystone/app/views/accessory_lines/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Bidsheet:</strong>
  <%= @accessory_line.bidSheet_id %>
</p>

<p>
  <strong>Accessory:</strong>
  <%= @accessory_line.accessory_id %>
</p>

<%= link_to 'Edit', edit_accessory_line_path(@accessory_line) %> |
<%= link_to 'Back', accessory_lines_path %>