Keystone2/config/routes.rb
Rails.application.routes.draw do

  get 'reports/complete_jobs_by_month', to: 'reports#complete_jobs_by_month', as: :complete_jobs_by_month

  get 'reports/sales_by_item_category', to: 'reports#item_sales_by_category', as: :item_sales_by_category

  get 'welcome/index'

  resources :misc_item_lines

  resources :accessory_lines

  resources :bid_sheets

  resources :concrete_slabs

  resources :accessories

  resources :transfer_switches

  resources :generators

  resources :customers

  resources :states

  resources :employees

root 'welcome#index'

  resources :reports

end

Keystone2/app/models/accessory.rb
class Accessory < ActiveRecord::Base
  include ActionView::Helpers::NumberHelper

  has_many :bid_sheets

#  validates :modelNumber, :productDescription, presence: true
#  validates :dealer, :msrp, numericality: true

  def desc_with_price
    "#{productDescription} - #{number_to_currency(dealer)}"
  end

end

Keystone2/app/models/accessory_line.rb
class AccessoryLine < ActiveRecord::Base
  belongs_to :accessory
  belongs_to :bid_sheet, :foreign_key => :bidSheet_id
end

Keystone2/app/models/bid_sheet.rb
class BidSheet < ActiveRecord::Base
  belongs_to :employee
  belongs_to :customer
  belongs_to :transfer_switch, :foreign_key => :transferswitch_id
  belongs_to :concrete_slab, :foreign_key => :concreteslab_id
  belongs_to :generator
  belongs_to :accessory

  validates :jobNumber, uniqueness: { scope: :jobNumber, message: "%Job number: {value} has already been used." }

end

Keystone2/app/models/concrete_slab.rb
class ConcreteSlab < ActiveRecord::Base
  include ActionView::Helpers::NumberHelper

  has_many :bid_sheets

  validates :slabName, :slabPrice, presence: true
  validates :slabPrice, numericality: true

  def name_with_price
    "#{slabName} - #{number_to_currency(slabPrice)}"
  end
end

Keystone2/app/models/customer.rb
class Customer < ActiveRecord::Base
  belongs_to :state
  has_many :bid_sheets

#  validates :firstName, :lastName, :streetAddress, :city, :state_id, :zipCode, :phone, presence: true
#  validates :firstName, :lastName, :city, format: { with: /\A[a-zA-Z]+\z/, message: "only allows letters." }
#  validates :phone2, length: {is:10}, numericality: {only_integer: true}, allow_blank: true
#  validates :phone, length: {is:10}, numericality: {only_integer: true}

  def set_cusfullname
    cusfullname = firstName + ' ' + lastName
    return cusfullname
  end

  def set_cusaddress
    cusaddress = streetAddress + ' ' + streetAddress2 + ', ' + city + ', ' + state.abbreviation + '  ' + zipCode.to_s
    return cusaddress
  end
end

Keystone2/app/models/employee.rb
class Employee < ActiveRecord::Base
  has_many :bid_sheets

  validates :firstName, :lastName, presence: true
  validates :firstName, :lastName, format: { with: /\A[a-zA-Z]+\z/, message: "only allows letters." }

  def set_empfullname
    empfullname = firstName + ' ' + lastName
    return empfullname
  end
end

Keystone2/app/models/generator.rb
class Generator < ActiveRecord::Base
  include ActionView::Helpers::NumberHelper

  has_many :bid_sheets

  validates :modelNumber, :productDescription, presence: true
  validates :dealer, :msrp, :map, numericality: true

  def model_with_price
    "#{modelNumber} - #{number_to_currency(dealer)}"
  end

end

Keystone2/app/models/transfer_switch.rb
class TransferSwitch < ActiveRecord::Base
  include ActionView::Helpers::NumberHelper

  has_many :bid_sheets

  def model_with_price
    "#{modelNumber} - #{number_to_currency(dealer)}"
  end

end

Keystone2/app/controllers/bid_sheets_controller.rb
class BidSheetsController < ApplicationController
  before_action :set_bid_sheet, only: [:show, :edit, :update, :destroy]

  # GET /bid_sheets
  # GET /bid_sheets.json
  def index
    @bid_sheets = BidSheet.all
    @accessories = Accessory.all
  end



  # GET /bid_sheets/1
  # GET /bid_sheets/1.json
  def show
  end

  # GET /bid_sheets/new
  def new
    @bid_sheet = BidSheet.new
  end

  # GET /bid_sheets/1/edit
  def edit
    @bid_sheet = BidSheet.find(params[:id])
  end

  # POST /bid_sheets
  # POST /bid_sheets.json
  def create
    @bid_sheet = BidSheet.new(bid_sheet_params)

    respond_to do |format|
      if @bid_sheet.save
        format.html { redirect_to @bid_sheet, notice: 'Bid sheet was successfully created.' }
        format.json { render :show, status: :created, location: @bid_sheet }
      else
        format.html { render :new }
        format.json { render json: @bid_sheet.errors, status: :unprocessable_entity }
      end
    end

  end

  # PATCH/PUT /bid_sheets/1
  # PATCH/PUT /bid_sheets/1.json
  def update
    respond_to do |format|
      if @bid_sheet.update(bid_sheet_params)
        format.html { redirect_to @bid_sheet, notice: 'Bid sheet was successfully updated.' }
        format.json { render :show, status: :ok, location: @bid_sheet }
      else
        format.html { render :edit }
        format.json { render json: @bid_sheet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bid_sheets/1
  # DELETE /bid_sheets/1.json
  def destroy
    @bid_sheet.destroy
    respond_to do |format|
      format.html { redirect_to bid_sheets_url, notice: 'Bid sheet was successfully destroyed.' }
      format.json { head :no_content }

    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_bid_sheet
    @bid_sheet = BidSheet.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def bid_sheet_params
    params.require(:bid_sheet).permit(:employee_id, :customer_id, :jobNumber, :date, :generator_id, :transferswitch_id,
                                      :concreteslab_id, :laborCost, :laborTax, :genAtsTax, :markup, :taxExempt, :description,
                                      :completeStatus, :gasLineInstallation, :gasFootage, :gasLength, :gasRegulator, :gasMeterUpgrade,
                                      :gasMeterUpgrade, :electricalSupply, :craneRigging, :deliveryShipping, :permits, :batteries,
                                      :miscItemName1, :miscItemPrice1, :miscItemName2, :miscItemPrice2, :miscItemName3, :miscItemPrice3,
                                      :accessory1, :accessory2, :accessory3, :accessory4, :accessory5, :accessory6, :accessory7,
                                      :accessory8, :accessory9, :accessory10)
  end
end

Keystone2/app/controllers/reports_controller.rb
class ReportsController < ApplicationController

  def bid_sheet_by_customer_date

  end

  def complete_jobs_by_month
    @bid_sheets = BidSheet.all
  end

  def item_sales_by_category
    @bid_sheets = BidSheet.all
  end
end

Keystone2/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

Keystone2/app/helpers/application_helper.rb
module ApplicationHelper
  def link_to_remove_fields(name, f)
    f.hidden_field(:_destroy) + link_to_function(name, "remove_fields(this)")
  end

  def link_to_add_fields(name, f, association)
    new_object = f.object.class.reflect_on_association(association).klass.new
    fields = f.fields_for(association, new_object, :child_index => "new_#{association}") do |builder|
      render(association.to_s.singularize + "_fields", :f => builder)
    end
    link_to_function(name, h("add_fields(this, \"#{association}\", \"#{escape_javascript(fields)}\")"))
  end
end

Keystone2/app/helpers/link_to_add_fields.rb
def link_to_add_fields(name, f, association)
  new_object = f.object.class.reflect_on_association(association).klass.new
  fields = f.fields_for(association, new_object, :child_index => "new_#{association}") do |builder|
    render(association.to_s.singularize + "_fields", :f => builder)
  end
  link_to_function(name, h("add_fields(this, \"#{association}\", \"#{escape_javascript(fields)}\")"))
end

Keystone2/app/helpers/link_to_function_helper.rb
module LinkToFunctionHelper
  def link_to_function(name, *args, &block)
    html_options = args.extract_options!.symbolize_keys

    function = block_given? ? update_page(&block) : args[0] || ''
    onclick = "#{"#{html_options[:onclick]}; " if html_options[:onclick]}#{function}; return false;"
    href = html_options[:href] || '#'

    content_tag(:a, name, html_options.merge(:href => href, :onclick => onclick))
  end
end

Keystone2/app/helpers/reports_helper.rb
module ReportsHelper
end

Keystone2/app/helpers/welcome_helper.rb
module WelcomeHelper
end

Keystone2/app/views/accessory_lines/index.html.erb
<h1>Listing Accessory Lines</h1>

<table>
  <thead>
    <tr>
      <th>Bid Sheet</th>
      <th>Accessory</th>
      <th>Dealer</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @accessory_lines.each do |accessory_line| %>
      <tr>
        <td><%= accessory_line.bid_sheet.jobNumber %></td>
        <td><%= accessory_line.accessory.productDescription %></td>
        <td><%= number_to_currency(accessory_line.accessory.dealer) %> </td>
        <td><%= link_to 'Show', accessory_line %></td>
        <td><%= link_to 'Edit', edit_accessory_line_path(accessory_line) %></td>
        <td><%= link_to 'Destroy', accessory_line, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Accessory line', new_accessory_line_path %>

Keystone2/app/views/bid_sheets/bid_sheet_by_customer_date.html.erb
<h1>Listing Bid Sheets</h1>
<table class="center">
  <tr>
    <td><h1>Complete Jobs for </h1></td>
    <td><select>
      <option value="1">January</option>
      <option value="2">February</option>
      <option value="3">March</option>
      <option value="4">April</option>
      <option value="5">May</option>
      <option value="6">June</option>
      <option value="7">July</option>
      <option value="8">August</option>
      <option value="9">September</option>
      <option value="10">October</option>
      <option value="11">November</option>
      <option value="12">December</option>
    </select></td>
    <td><select id="year" name="year">
      <script>
          var myDate = new Date();
          var year = myDate.getFullYear()+20;
          for(var i = 2014; i < year+1; i++){
              document.write('<option value="'+i+'">'+i+'</option>');
          }
      </script>
    </select></td>
    <td><button type="button" onclick="alert('Hello world!')">Go</button></td>
  </tr>
</table>

<hr>

<table>
  <thead>
  <tr>
    <th>Employee</th>
    <th>Customer</th>
    <th>Job #</th>
    <th>Date</th>
    <th>Labor Cost</th>
    <th>Generator</th>
    <th>Markup</th>
    <th>Tax Status</th>
    <th>Description</th>
    <th>Complete</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @bid_sheets.each do |bid_sheet| %>
      <tr>
        <td><%= bid_sheet.employee.set_empfullname %></td>
        <td><%= bid_sheet.customer.set_cusfullname %></td>
        <td><%= bid_sheet.jobNumber %></td>
        <td><%= bid_sheet.date %></td>
        <td><%= number_to_currency(bid_sheet.laborCost) %></td>
        <td><%= bid_sheet.generator.modelNumber %></td>
        <td><%= bid_sheet.markup %>%</td>
        <td><%= bid_sheet.taxExempt %></td>
        <td><%= bid_sheet.description %></td>
        <td><%= bid_sheet.completeStatus %></td>
        <td><%= link_to 'Show', bid_sheet %></td>
        <td><%= link_to 'Edit', edit_bid_sheet_path(bid_sheet) %></td>
        <td><%= link_to 'Destroy', bid_sheet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
  <% end %>
  <tr>
    <td><b>Totals</b></td>
    <td></td>
    <td></td>
    <td></td>
    <td><b><%= number_to_currency(BidSheet.sum(:laborCost)) %></b></td>
    <td></td>
    <td><%= BidSheet.average(:markup) %>%</td>
    <td></td>
    <td></td>
    <td></td>
  </tr>
  </tbody>
</table>

<br>

<%= link_to 'New Bid sheet', new_bid_sheet_path %>

Keystone2/app/views/bid_sheets/index.html.erb
<h1>Listing Bid Sheets</h1>

<table class="center">
  <thead>
  <tr>
    <th>Employee</th>
    <th>Customer</th>
    <th>Job #</th>
    <th>Date</th>
    <th>Labor Cost</th>
    <th>Generator</th>
    <th>Markup</th>
    <th>Tax Status</th>
    <th>Description</th>
    <th>Complete</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @bid_sheets.each do |bid_sheet| %>
      <tr>
        <td><%= bid_sheet.employee.set_empfullname %></td>
        <td><%= bid_sheet.customer.set_cusfullname %></td>
        <td><%= bid_sheet.jobNumber %></td>
        <td><%= bid_sheet.date %></td>
        <td><%= number_to_currency(bid_sheet.laborCost) %></td>
        <td><%= bid_sheet.generator.modelNumber %></td>
        <td><%= bid_sheet.markup %>%</td>
        <td><%= bid_sheet.taxExempt %></td>
        <td><%= bid_sheet.description %></td>
        <td><%= bid_sheet.completeStatus %></td>
        <td><%= link_to 'Proposal/Invoice', bid_sheet %></td>
        <td><%= link_to 'Edit', edit_bid_sheet_path(bid_sheet) %></td>
        <td><%= link_to 'Destroy', bid_sheet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
  <% end %>
  <tr>
    <td><b>Totals</b></td>
    <td></td>
    <td></td>
    <td></td>
    <td><b><%= number_to_currency(BidSheet.sum(:laborCost)) %></b></td>
    <td></td>
    <td><%= BidSheet.average(:markup) %>%</td>
    <td></td>
    <td></td>
    <td></td>
  </tr>
  </tbody>
</table>

<div class="center">
  <%= link_to 'New Bid sheet', new_bid_sheet_path %>
</div>

Keystone2/app/views/bid_sheets/sales_by_item_category.html.erb
<h1>Sales by Item Category</h1>

Keystone2/app/views/bid_sheets/show.html.erb
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset='UTF-8'>

  <title>Editable Invoice</title>

  <link rel='stylesheet' href='css/style.css'>
  <link rel='stylesheet' href='css/print.css' media="print">
  <script src='js/jquery-1.3.2.min.js'></script>
  <script src='js/example.js'></script>


</head>

<body>

<% genAtsCost = @bid_sheet.generator.dealer + @bid_sheet.transfer_switch.dealer  %>



<% matLaborCost = @bid_sheet.concrete_slab.slabPrice + @bid_sheet.gasLineInstallation +
        (@bid_sheet.gasFootage * @bid_sheet.gasLength) + @bid_sheet.gasRegulator + @bid_sheet.gasMeterUpgrade +
        @bid_sheet.electricalSupply + @bid_sheet.craneRigging + @bid_sheet.deliveryShipping + @bid_sheet.permits +
        @bid_sheet.batteries + Accessory.find(@bid_sheet.accessory1).dealer + Accessory.find(@bid_sheet.accessory2).dealer +
        Accessory.find(@bid_sheet.accessory3).dealer + Accessory.find(@bid_sheet.accessory4).dealer +
        Accessory.find(@bid_sheet.accessory5).dealer + Accessory.find(@bid_sheet.accessory6).dealer + Accessory.find(@bid_sheet.accessory7).dealer +
        Accessory.find(@bid_sheet.accessory8).dealer + Accessory.find(@bid_sheet.accessory9).dealer + Accessory.find(@bid_sheet.accessory10).dealer +
        @bid_sheet.miscItemPrice1 + @bid_sheet.miscItemPrice2 + @bid_sheet.miscItemPrice3 + @bid_sheet.laborCost%>


<% number_to_currency(genAtsCost + matLaborCost) %>

<% genatsTax = genAtsCost * (@bid_sheet.genAtsTax / 100) %>

<% laborTax =  ( @bid_sheet.laborCost * ( @bid_sheet.laborTax / 100 ) ) %>

<!--Price before Tax -->
<% preTaxPrice =  (genAtsCost + matLaborCost) * (1 + (@bid_sheet.markup / 100)) %>
<% number_to_currency(preTaxPrice) %>

<!--Total Tax -->
<% number_to_currency( genatsTax + laborTax ) %>

<!--Total Price -->
<% number_to_currency( preTaxPrice + ( genatsTax + laborTax ) ) %>


<div id="page-wrap">

  <textarea id="header">PROPOSAL</textarea>

  <table>
    <tr>
      <div id="identity">
        <td class="borderb">
          <p>
          <div id="logo">
            <%= image_tag("kiss.PNG", :alt => "logo") %>
          </div>
          </p>
        </td>

        <td class="borderb">
          <p>
            <strong>Bill To:</strong></br></br>

            <%= @bid_sheet.customer.set_cusfullname %> </br>
            <%= @bid_sheet.customer.set_cusaddress %> </br>
          </p>
        </td>

      </div>
    </tr>
  </table>

  <div style="clear:both"></div>

  <div id="customer">

    <table id="meta">
      <tr>
        <td class="meta-head">Job #</td>
        <td><%= @bid_sheet.jobNumber %></td>
      </tr>
      <tr>

        <td class="meta-head">Date</td>
        <td><textarea id="date"><%= @bid_sheet.date %></textarea></td>
      </tr>
      <tr>
        <td class="meta-head">Total</td>
        <td><div class="due"><%= number_to_currency( preTaxPrice + ( genatsTax + laborTax ) ) %></div></td>
      </tr>

    </table>

  </div>




  <div id="summary">
    <h5>Summary</h5>

    <section>
      <textarea style="height: 420px; !important;">Kiss Generator Kohler <%= @bid_sheet.generator.productDescription %> Proposal

        Thank you for asking KISS Generator Inc. to make a proposal for the standard power for your home/office located at <%= @bid_sheet.customer.set_cusaddress %>.

        The pricing includes the installation of Kohler <%= @bid_sheet.generator.productDescription %>,<%= @bid_sheet.transfer_switch.modelNumber %> transfer switch, and the following accessories:

        <%= Accessory.find(@bid_sheet.accessory1).productDescription %>
        <%= Accessory.find(@bid_sheet.accessory2).productDescription %>
        <%= Accessory.find(@bid_sheet.accessory3).productDescription %>
        <%= Accessory.find(@bid_sheet.accessory4).productDescription %>
        <%= Accessory.find(@bid_sheet.accessory5).productDescription %>
        <%= Accessory.find(@bid_sheet.accessory6).productDescription %>
        <%= Accessory.find(@bid_sheet.accessory7).productDescription %>
        <%= Accessory.find(@bid_sheet.accessory8).productDescription %>
        <%= Accessory.find(@bid_sheet.accessory9).productDescription %>
        <%= Accessory.find(@bid_sheet.accessory10).productDescription %>

        Your generator will be ordered after receiving your deposit with a x-x week delivery. A 50% deposit is required at time of ordering, an additional 40% with timely installation and balance due at commissioning. We also have a no return policy after the order has been placed. The process to acquire permits and engineering also begins when the order is confirmed. In addition we will contact Center Point on your behalf to have your gas service installed so when the permits are approved we can begin other preparations needed to complete your project. If you have any questions please contact me. "Thank You" for the opportunity to be a part of the bidding process...

        </textarea>

      <div id="terms">
        <textarea>Enter additional job description</textarea>
      </div>
    </section>

  </div>

  <table id="items">

    <tr>

      <td colspan="2" class="total-line">Subtotal</td>
      <td class="total-value"><div id="subtotal"><%= number_to_currency(preTaxPrice) %></div></td>
    </tr>

    <tr>

      <td colspan="2" class="total-line">Tax</td>
      <td class="total-value"><div id="subtotal"><%= number_to_currency( genatsTax + laborTax ) %></div></td>
    </tr>
    <tr>


      <td colspan="2" class="total-line">Total</td>
      <td class="total-value"><div id="total"><%= number_to_currency( preTaxPrice + ( genatsTax + laborTax ) ) %></div></td>
    </tr>
    <tr>

      <td colspan="2" class="total-line">Amount Paid</td>

      <td class="total-value"><textarea id="paid">$0.00</textarea></td>
    </tr>
    <tr>

      <td colspan="2" class="total-line">Balance Due</td>
      <td class="total-value"><textarea id="paid">$0.00</textarea></td>
    </tr>

  </table>

  <div id="terms">
    <h5>Terms</h5>
    <textarea>Any amendments requested by the City of Houston Building Inspection Office or any emergency concerns will be addressed and pricing may need to change accordingly.</textarea>
  </div>


  </br></br></br>
  <table>
    <tr>
      <td class="borderb">


        ____________________________________________
      </td>
      <td class="borderb">


        __________
      </td>
    </tr>
    <tr>
      <td class="borderb">
        <textarea style="height: 10px; !important;">Customer</textarea>
      </td>
      <td class="borderb">
        Date
      </td>
    </tr>
    <tr>
      <td class="borderb">


        ____________________________________________
      </td>
      <td class="borderb">


        __________
      </td>
    </tr>
    <tr>
      <td class="borderb">
        <textarea style="height: 10px; !important;">Burt Koenig</textarea>
      </td>
      <td class="borderb">
        Date
      </td>
    </tr>
  </table>
  </p>

</div>



</body>

</html>

<%= link_to 'Edit', edit_bid_sheet_path(@bid_sheet) %> |
<%= link_to 'Back', bid_sheets_path %>

Keystone2/app/views/concrete_slabs/index.html.erb
<h1>Listing Concrete Slabs</h1>

<table class="center">
  <thead>
    <tr>
      <th>Description</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @concrete_slabs.each do |concrete_slab| %>
      <tr>
        <td><%= concrete_slab.slabName %></td>
        <td><%= number_to_currency(concrete_slab.slabPrice) %></td>
        <td><%= link_to 'Edit', edit_concrete_slab_path(concrete_slab) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<p class="center"><%= link_to 'New Concrete slab', new_concrete_slab_path %></p>

Keystone2/app/views/concrete_slabs/show.html.erb
<div class="center">

<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @concrete_slab.slabName %>
</p>

<p>
  <strong>Price:</strong>
  <%= number_to_currency(@concrete_slab.slabPrice) %>
</p>

<%= link_to 'Edit', edit_concrete_slab_path(@concrete_slab) %> |
<%= link_to 'Back', concrete_slabs_path %>

</div>

Keystone2/app/views/customers/index.html.erb
<h1>Listing Customers</h1>

<table class="center">
  <thead>
    <tr>
      <th>First Name</th>
      <th>Last Name</th>
      <th>Address 1</th>
      <th>Address 2</th>
      <th>City</th>
      <th>State</th>
      <th>ZIP Code</th>
      <th>Phone</th>
      <th>Phone 2</th>
      <th>Email</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @customers.each do |customer| %>
      <tr>
        <td><%= customer.firstName %></td>
        <td><%= customer.lastName %></td>
        <td><%= customer.streetAddress %></td>
        <td><%= customer.streetAddress2 %></td>
        <td><%= customer.city %></td>
        <td><%= customer.state.abbreviation %></td>
        <td><%= customer.zipCode %></td>
        <td><%= number_to_phone(customer.phone) %></td>
        <td><%= number_to_phone(customer.phone2) %></td>
        <td><%= customer.email %></td>
        <td><%= link_to 'Show', customer %></td>
        <td><%= link_to 'Edit', edit_customer_path(customer) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<div class="center">
<%= link_to 'New Customer', new_customer_path %>
</div>

Keystone2/app/views/employees/index.html.erb
<h1>Listing Employees</h1>

<table class="center">
  <thead>
    <tr>
      <th>First Name</th>
      <th>Last Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @employees.each do |employee| %>
      <tr>
        <td><%= employee.firstName %></td>
        <td><%= employee.lastName %></td>
        <td><%= link_to 'Edit', edit_employee_path(employee) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<div class="center">
<%= link_to 'New Employee', new_employee_path %>
</div>

Keystone2/app/views/employees/show.html.erb
<p id="notice"><%= notice %></p>
<div class="center">
<p>
  <strong>First Name:</strong>
  <%= @employee.firstName %>
</p>

<p>
  <strong>Last Name:</strong>
  <%= @employee.lastName %>
</p>

<%= link_to 'Edit', edit_employee_path(@employee) %> |
<%= link_to 'Back', employees_path %>
</div>

Keystone2/app/views/transfer_switches/index.html.erb
<h1>Listing Transfer Switches</h1>

<table class="center">
  <thead>
    <tr>
      <th>Description</th>
      <th>Model #</th>
      <th>Dealer</th>
      <th>MSRP</th>
      <th>MAP</th>
      <th>Active</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @transfer_switches.each do |transfer_switch| %>
      <tr>
        <td><%= transfer_switch.productDescription %></td>
        <td><%= transfer_switch.modelNumber %></td>
        <td><%= number_to_currency(transfer_switch.dealer) %></td>
        <td><%= number_to_currency(transfer_switch.msrp) %></td>
        <td><%= number_to_currency(transfer_switch.map) %></td>
        <td><%= transfer_switch.activeStatus %></td>
        <td><%= link_to 'Edit', edit_transfer_switch_path(transfer_switch) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<div class="center">
<%= link_to 'New Transfer switch', new_transfer_switch_path %>
</div>

Keystone2/app/views/transfer_switches/show.html.erb
<div class="center">
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @transfer_switch.productDescription %>
</p>

<p>
  <strong>Model #:</strong>
  <%= @transfer_switch.modelNumber %>
</p>

<p>
  <strong>Dealer:</strong>
  <%= number_to_currency(@transfer_switch.dealer) %>
</p>

<p>
  <strong>MSRP:</strong>
  <%= number_to_currency(@transfer_switch.msrp) %>
</p>

<p>
  <strong>MAP:</strong>
  <%= number_to_currency(@transfer_switch.map) %>
</p>

<p>
  <strong>Active:</strong>
  <%= @transfer_switch.activeStatus %>
</p>

<%= link_to 'Edit', edit_transfer_switch_path(@transfer_switch) %> |
<%= link_to 'Back', transfer_switches_path %>
</div>

Keystone2/app/views/welcome/index.html.erb
<h1>KISS Generators Bid Sheet System</h1>


<center> <%= image_tag("kiss1.png", :alt => "logo") %></center>

<center>
  <h3>Reports</h3>
  <h5>
    <%= link_to "Complete Jobs by Month", complete_jobs_by_month_path %></br>
    <%= link_to "Sales by Item Category", item_sales_by_category_path %>
  </h5>
</center>