Keystone/config/routes.rb
Rails.application.routes.draw do
  resources :bid_sheets

  resources :misc_item_lines

  resources :accessory_lines

  resources :customers

  resources :concrete_slabs

  resources :misc_items

  resources :accessories

  resources :transfer_switches

  resources :generators

  resources :states

  resources :employees

end

Keystone/app/models/accessory.rb
class Accessory < ActiveRecord::Base
  has_many :bid_sheets
  has_many :accessory_lines, :through => :bid_sheets
end

Keystone/app/models/accessory_line.rb
class AccessoryLine < ActiveRecord::Base
  belongs_to :accessory
  belongs_to :bid_sheet
end

Keystone/app/models/bid_sheet.rb
class BidSheet < ActiveRecord::Base
  belongs_to :employee
  belongs_to :customer
  belongs_to :generator
  belongs_to :transfer_switch
  belongs_to :concrete_slab

  has_many :accessory_lines
  has_many :accessories, :through => :accessory_lines

  has_many :misc_item_lines
  has_many :misc_items, :through => :misc_item_lines
end

Keystone/app/models/concrete_slab.rb
class ConcreteSlab < ActiveRecord::Base
  has_many :bid_sheets
end

Keystone/app/models/customer.rb
class Customer < ActiveRecord::Base
  belongs_to :state
  has_many :bid_sheets
end

Keystone/app/models/employee.rb
class Employee < ActiveRecord::Base
  has_many :bid_sheets
end

Keystone/app/models/generator.rb
class Generator < ActiveRecord::Base
  has_many :bid_sheets
end

Keystone/app/models/misc_item.rb
class MiscItem < ActiveRecord::Base
  has_many :bid_sheets
  has_many :misc_item_lines, :through => :bid_sheets
end

Keystone/app/models/misc_item_line.rb
class MiscItemLine < ActiveRecord::Base
  belongs_to :misc_item
  belongs_to :bid_sheet
end

Keystone/app/models/state.rb
class State < ActiveRecord::Base
  has_many :customers
end

Keystone/app/models/transfer_switch.rb
class TransferSwitch < ActiveRecord::Base
  has_many :bid_sheets
end

Keystone/app/controllers/accessories_controller.rb
class AccessoriesController < ApplicationController
  before_action :set_accessory, only: [:show, :edit, :update, :destroy]

  # GET /accessories
  # GET /accessories.json
  def index
    @accessories = Accessory.all
  end

  # GET /accessories/1
  # GET /accessories/1.json
  def show
  end

  # GET /accessories/new
  def new
    @accessory = Accessory.new
  end

  # GET /accessories/1/edit
  def edit
  end

  # POST /accessories
  # POST /accessories.json
  def create
    @accessory = Accessory.new(accessory_params)

    respond_to do |format|
      if @accessory.save
        format.html { redirect_to @accessory, notice: 'Accessory was successfully created.' }
        format.json { render :show, status: :created, location: @accessory }
      else
        format.html { render :new }
        format.json { render json: @accessory.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /accessories/1
  # PATCH/PUT /accessories/1.json
  def update
    respond_to do |format|
      if @accessory.update(accessory_params)
        format.html { redirect_to @accessory, notice: 'Accessory was successfully updated.' }
        format.json { render :show, status: :ok, location: @accessory }
      else
        format.html { render :edit }
        format.json { render json: @accessory.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accessories/1
  # DELETE /accessories/1.json
  def destroy
    @accessory.destroy
    respond_to do |format|
      format.html { redirect_to accessories_url, notice: 'Accessory was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_accessory
      @accessory = Accessory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def accessory_params
      params.require(:accessory).permit(:productDescription, :modelNumber, :dealer, :msrp)
    end
end

Keystone/app/controllers/states_controller.rb
class StatesController < ApplicationController
  before_action :set_state, only: [:show, :edit, :update, :destroy]

  # GET /states
  # GET /states.json
  def index
    @states = State.all
  end

  # GET /states/1
  # GET /states/1.json
  def show
  end

  # GET /states/new
  def new
    @state = State.new
  end

  # GET /states/1/edit
  def edit
  end

  # POST /states
  # POST /states.json
  def create
    @state = State.new(state_params)

    respond_to do |format|
      if @state.save
        format.html { redirect_to @state, notice: 'State was successfully created.' }
        format.json { render :show, status: :created, location: @state }
      else
        format.html { render :new }
        format.json { render json: @state.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /states/1
  # PATCH/PUT /states/1.json
  def update
    respond_to do |format|
      if @state.update(state_params)
        format.html { redirect_to @state, notice: 'State was successfully updated.' }
        format.json { render :show, status: :ok, location: @state }
      else
        format.html { render :edit }
        format.json { render json: @state.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /states/1
  # DELETE /states/1.json
  def destroy
    @state.destroy
    respond_to do |format|
      format.html { redirect_to states_url, notice: 'State was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_state
      @state = State.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def state_params
      params.require(:state).permit(:name, :abbreviation)
    end
end

Keystone/app/helpers/accessories_helper.rb
module AccessoriesHelper
end

Keystone/app/helpers/accessory_lines_helper.rb
module AccessoryLinesHelper
end

Keystone/app/helpers/application_helper.rb
module ApplicationHelper
end

Keystone/app/helpers/bid_sheets_helper.rb
module BidSheetsHelper
end

Keystone/app/helpers/concrete_slabs_helper.rb
module ConcreteSlabsHelper
end

Keystone/app/helpers/customers_helper.rb
module CustomersHelper
end

Keystone/app/helpers/employees_helper.rb
module EmployeesHelper
end

Keystone/app/helpers/generators_helper.rb
module GeneratorsHelper
end

Keystone/app/helpers/misc_items_helper.rb
module MiscItemsHelper
end

Keystone/app/helpers/states_helper.rb
module StatesHelper
end

Keystone/app/views/accessories/_form.html.erb
<%= form_for(@accessory) do |f| %>
  <% if @accessory.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@accessory.errors.count, "error") %> prohibited this accessory from being saved:</h2>

      <ul>
      <% @accessory.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :productDescription %><br>
    <%= f.text_field :productDescription %>
  </div>
  <div class="field">
    <%= f.label :modelNumber %><br>
    <%= f.text_field :modelNumber %>
  </div>
  <div class="field">
    <%= f.label :dealer %><br>
    <%= f.text_field :dealer %>
  </div>
  <div class="field">
    <%= f.label :msrp %><br>
    <%= f.text_field :msrp %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Keystone/app/views/accessories/edit.html.erb
<h1>Editing accessory</h1>

<%= render 'form' %>

<%= link_to 'Show', @accessory %> |
<%= link_to 'Back', accessories_path %>

Keystone/app/views/accessories/index.html.erb
<h1>Listing accessories</h1>

<table>
  <thead>
    <tr>
      <th>Productdescription</th>
      <th>Modelnumber</th>
      <th>Dealer</th>
      <th>Msrp</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @accessories.each do |accessory| %>
      <tr>
        <td><%= accessory.productDescription %></td>
        <td><%= accessory.modelNumber %></td>
        <td><%= accessory.dealer %></td>
        <td><%= accessory.msrp %></td>
        <td><%= link_to 'Show', accessory %></td>
        <td><%= link_to 'Edit', edit_accessory_path(accessory) %></td>
        <td><%= link_to 'Destroy', accessory, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Accessory', new_accessory_path %>

Keystone/app/views/accessories/new.html.erb
<h1>New accessory</h1>

<%= render 'form' %>

<%= link_to 'Back', accessories_path %>

Keystone/app/views/accessories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Productdescription:</strong>
  <%= @accessory.productDescription %>
</p>

<p>
  <strong>Modelnumber:</strong>
  <%= @accessory.modelNumber %>
</p>

<p>
  <strong>Dealer:</strong>
  <%= @accessory.dealer %>
</p>

<p>
  <strong>Msrp:</strong>
  <%= @accessory.msrp %>
</p>

<%= link_to 'Edit', edit_accessory_path(@accessory) %> |
<%= link_to 'Back', accessories_path %>